FROM openjdk:11
ADD target/Personal-Project-URL-Shortener-0.0.1-SNAPSHOT.jar Personal-Project-URL-Shortener-0.0.1-SNAPSHOT.jar
EXPOSE 8040
ENTRYPOINT ["java", "-jar", "Personal-Project-URL-Shortener-0.0.1-SNAPSHOT.jar"]